"""Regenerate src/theme-tokens.css from ui/theme.py.

ui/theme.py's Theme dataclass is the single source of truth for chat panel
colors; this script is the only place that reads it into CSS so the two
never drift into hand-copied, independently-edited color tables. Run via
`npm run build`'s prebuild step (see package.json); never edit the
generated file directly.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from desktop_viewer.ui.theme import THEMES  # noqa: E402

OUTPUT_PATH = Path(__file__).resolve().parent.parent / "src" / "theme-tokens.css"

HEADER = (
    "/* Generated by chat_ui_src/scripts/export_theme_tokens.py"
    " from src/desktop_viewer/ui/theme.py. */\n"
    "/* Do not edit directly - ui/theme.py is the single source of truth. */\n\n"
)


def _block(theme) -> str:
    return (
        f'[data-theme="{theme.name}"] {{\n'
        f"  --chat-background: {theme.chat_background};\n"
        f"  --chat-foreground: {theme.chat_foreground};\n"
        f"  --chat-muted: {theme.chat_muted};\n"
        f"  --chat-border: {theme.chat_border};\n"
        f"}}\n"
    )


def main() -> None:
    body = "\n".join(_block(theme) for theme in THEMES.values())
    OUTPUT_PATH.write_text(HEADER + body, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
